use_frameworks!

platform :ios, '8.0'

target 'NBLSideSlipFilter_Example' do
  pod 'NBLSideSlipFilter', :path => '../'

  target 'NBLSideSlipFilter_Tests' do
    inherit! :search_paths

    
  end
end
